---
- name: Remove Old Versions
  ansible.builtin.dnf:
    name:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest 
      - docker-latest-logrotate
      - docker-logrotate 
      - docker-engine
    state: absent

- name: Install Repository Tools
  ansible.builtin.dnf:
    name:
      - yum-utils
    state: present

- name: Install Docker RPM Repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    file: docker-ce
    gpgcheck: true 
    enabled: true 
    gpgkey:
      - '{{ gpgkey_url }}'

- name: Add GPG Key to RPM Keyring
  ansible.builtin.rpm_key:
    state: present
    key: '{{ gpgkey_url }}'

- name: Install Docker Packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Install Python Modules
  ansible.builtin.dnf:
    name:
      - python3-setuptools
      - python3-pip
    state: present

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker
  when:
    - configure_ansible_user

- name: Configure Docker Daemon
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
    owner: root
    group: root

- name: Remove Host Call in systemd Configuration
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: "^ExecStart=/usr/bin/dockerd -H"
    line: "ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock"
    state: present

- name: Update firewalld Firewall
  ansible.posix.firewalld:
    port: "{{ docker_port }}-{{ docker_tls_port }}/tcp"
    source: '{{ item }}'
    permanent: true
    immediate: true
  loop: '{{ valid_sources }}'
  when:
    - enable_firewalld

- name: Issue daemon-reload for new Config 
  ansible.builtin.systemd_service:
    name: docker
    daemon_reload: true
    state: reloaded

- name: Enable Docker Service on System Start
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Enable containerd Service on System Start
  ansible.builtin.service:
    name: containerd.service
    enabled: true
    state: started
